# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    app.twig_helper_vista:
        class: AppBundle\Twig\HelperVistas
        public: true
        tags: 
            - { name: twig.extension }
            
    app.twig_filter_vista:
        class: AppBundle\Twig\FiltersVista
        public: true
        tags:
            - { name: twig.extension }
    
